#!/bin/sh

# script call is: /etc/ucarp/script.d/vip-down eth0 192.168.1.50 [ADDIPLIST]
# 
# ADDIPLIST: comma separated list of additional IP adresses that will be addes to the interface
#   e.g: /etc/ucarp/script.d/vip-up eth0 192.168.1.50 "192.168.1.51,192.168.1.53,192.168.1.55" 
#
# We do need arping from iputils package to send gratious arp to inform switches about location of the new IP address!

. /etc/ucarp/script.d/scripthelpers.inc

NETMASK="`getnetmask $1`"

$BIN_IP address del $2/$NETMASK dev $1


# handling of additional ip addresses

if [ -n "$3" ] ;
then
	# we do have a list of additional ip addresses

	OLD_IFS="$IFS"

	IFS=","

	for ADDIP in "$3" 
	do
		# set IP
		$NIM_IP address del $ADDIP/$NETMASK dev $1

	done

	IFS="$OLD_IFS"

fi


